version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Running Tests
      - npm run test
      - npm run start
  post_build:
    commands:
      - echo Build completed on `date`
#reports:
  #jest_reports:
    #files:
     # - jest-junit.xml
    #file-format: JUNITXML
    #base-directory: ./testing-reports
